"""DOCX -> IEEEtran LaTeX skeleton.

Deterministic conversion of a Word manuscript (as produced by IEEE's Word template or a plain
draft) into a compilable ``IEEEtran`` conference project:

* title (first Title/Heading-0 paragraph or ``--title``), authors block as a ``\\todo``
* numbered/unnumbered headings (Heading 1-3 styles, or ``I. ``/``A. `` numbering) -> section levels
* ``Abstract``/``Index Terms`` paragraphs -> ``abstract`` / ``IEEEkeywords`` environments
* bold/italic/superscript runs -> ``\\textbf``/``\\emph``/``\\textsuperscript``
* numeric citations ``[4]``, ``[8]–[10]`` -> ``\\cite{refN}`` keys, reference list -> ``references.bib`` (@misc,
  marked for verification with ``paper-agent verify-refs`` after the seed is curated)
* tables -> ``tabular`` with booktabs; embedded images -> ``figures/figN.ext`` + ``\\includegraphics``
* special characters escaped; equations are kept as text inside ``\\todo{equation}``

The output is a *starting point* that compiles; a human (or the review/translate commands) finishes it.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from docx import Document
from docx.oxml.ns import qn

SPECIALS = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
            "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
CITE_RE = re.compile(r"\[(\d+)\]\s*(?:–|-{1,2})\s*\[(\d+)\]|\[(\d+)(?:\s*(?:–|-{1,2})\s*(\d+))?\]")  # runs are escaped first: – -> --
REF_LINE_RE = re.compile(r"^\s*\[(\d+)\]\s*(.+)$")
HEADING_NUM_RE = re.compile(r"^(?:(?P<roman>[IVX]+)\.|(?P<alpha>[A-Z])\.|(?P<num>\d+(?:\.\d+)*)\.?)\s+(?P<text>.+)$")

MAIN_TEMPLATE = r"""% Generated by paper-agent docx2tex from {src}
\documentclass[conference]{{IEEEtran}}
\IEEEoverridecommandlockouts
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{cite}}
\usepackage{{amsmath,amssymb,amsfonts}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{array}}
\usepackage{{xcolor}}
\usepackage{{url}}
\usepackage[hidelinks]{{hyperref}}
\graphicspath{{{{figures/}}}}
\newcommand{{\todo}}[1]{{\textcolor{{red}}{{[TODO: #1]}}}}

\begin{{document}}

\title{{{title}}}

\author{{%
{authors}}}

\maketitle

\input{{sections/body}}

\bibliographystyle{{IEEEtran}}
\bibliography{{references}}

\end{{document}}
"""


def esc(s: str) -> str:
    s = s.replace("\u2019", "'").replace("\u2018", "`").replace("\u201c", "``").replace("\u201d", "''")
    s = s.replace("\u2013", "--").replace("\u2014", "---").replace("\u00a0", "~")
    return "".join(SPECIALS.get(c, c) for c in s)


def run_tex(run) -> str:
    t = esc(run.text)
    if not t.strip():
        return t
    if run.font.superscript:
        t = f"\\textsuperscript{{{t}}}"
    elif run.font.subscript:
        t = f"\\textsubscript{{{t}}}"
    if run.bold:
        t = f"\\textbf{{{t}}}"
    if run.italic:
        t = f"\\emph{{{t}}}"
    return t


def para_tex(p, cite_keys: Dict[int, str]) -> str:
    parts = []
    prev = None
    for r in p.runs:
        if prev is not None and run_sig(r) == run_sig(prev):   # merge runs with identical formatting
            parts[-1] = (parts[-1][0] + r.text, r)
        else:
            parts.append((r.text, r))
        prev = r
    out = []
    for text, r in parts:
        fake = _Run(text, r)
        out.append(run_tex(fake))
    s = "".join(out)
    return CITE_RE.sub(lambda m: _cite(m, cite_keys), s)


def _cite(m, cite_keys: Dict[int, str]) -> str:
    a = int(m.group(1) or m.group(3))
    b = int(m.group(2) or m.group(4)) if (m.group(2) or m.group(4)) else None
    nums = list(range(a, b + 1)) if b and b > a else [a]
    keys = [cite_keys.setdefault(n, f"ref{n}") for n in nums]
    return "\\cite{" + ",".join(keys) + "}"


def run_sig(r) -> tuple:
    return (bool(r.bold), bool(r.italic), bool(r.font.superscript), bool(r.font.subscript))


class _Run:
    """Minimal run-like object for merged runs."""

    def __init__(self, text: str, like) -> None:
        self.text = text
        self.bold, self.italic, self.font = like.bold, like.italic, like.font


def heading_level(p) -> Optional[int]:
    style = (p.style.name if p.style is not None else "") or ""
    m = re.match(r"Heading (\d)", style)
    if m:
        return int(m.group(1))
    if style == "Title":
        return 0
    text = p.text.strip()
    hm = HEADING_NUM_RE.match(text)
    if hm and len(text) < 90 and not text.endswith("."):
        if hm.group("roman"):
            return 1
        if hm.group("alpha"):
            return 2
        if hm.group("num"):
            return min(3, hm.group("num").count(".") + 1)
    if text.isupper() and 3 < len(text) < 60 and not text.startswith("["):
        return 1
    return None


def heading_text(p) -> str:
    text = p.text.strip()
    m = HEADING_NUM_RE.match(text)
    text = m.group("text") if m else text
    return text.title() if text.isupper() else text


def iter_blocks(doc):
    """Body paragraphs and tables in document order."""
    body = doc.element.body
    for child in body.iterchildren():
        if child.tag == qn("w:p"):
            from docx.text.paragraph import Paragraph
            yield "p", Paragraph(child, doc)
        elif child.tag == qn("w:tbl"):
            from docx.table import Table
            yield "t", Table(child, doc)


def table_tex(t, idx: int, cite_keys: Dict[int, str]) -> str:
    rows = []
    for row in t.rows:
        cells, seen = [], set()
        for c in row.cells:
            if id(c._tc) in seen:
                continue
            seen.add(id(c._tc))
            cells.append(" ".join(para_tex(p, cite_keys) for p in c.paragraphs).strip())
        rows.append(cells)
    if not rows:
        return ""
    ncol = max(len(r) for r in rows)
    spec = "l" * ncol
    lines = ["\\begin{table}[t]", f"  \\caption{{\\todo{{Table {idx} caption}}}}", f"  \\label{{tab:{idx}}}",
             "  \\centering", "  \\small", f"  \\begin{{tabular}}{{@{{}}{spec}@{{}}}}", "    \\toprule",
             "    " + " & ".join(rows[0] + [""] * (ncol - len(rows[0]))) + " \\\\", "    \\midrule"]
    for r in rows[1:]:
        lines.append("    " + " & ".join(r + [""] * (ncol - len(r))) + " \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def extract_images(doc, p, fig_dir: Path, counter: List[int]) -> List[str]:
    """Save pictures embedded in paragraph ``p``; return LaTeX figure blocks."""
    out = []
    for blip in p._p.iter(qn("a:blip")):
        rid = blip.get(qn("r:embed"))
        if not rid or rid not in doc.part.related_parts:
            continue
        part = doc.part.related_parts[rid]
        ext = Path(part.partname).suffix or ".png"
        counter[0] += 1
        name = f"fig{counter[0]}{ext}"
        fig_dir.mkdir(parents=True, exist_ok=True)
        (fig_dir / name).write_bytes(part.blob)
        out.append("\n".join(["\\begin{figure}[t]", "  \\centering",
                              f"  \\includegraphics[width=\\columnwidth]{{{name}}}",
                              f"  \\caption{{\\todo{{Figure {counter[0]} caption}}}}", f"  \\label{{fig:{counter[0]}}}",
                              "\\end{figure}"]))
    return out


def references_bib(ref_lines: List[Tuple[int, str]], cite_keys: Dict[int, str]) -> str:
    out = ["% Generated by paper-agent docx2tex: raw reference strings as @misc entries.",
           "% Curate paper/references_seed.yaml and run `paper-agent verify-refs` to replace them.", ""]
    for n, text in ref_lines:
        key = cite_keys.setdefault(n, f"ref{n}")
        year = re.search(r"\b(19|20)\d{2}\b", text)
        out.append(f"@misc{{{key},\n  title = {{{{{esc(text)}}}}},\n  year = {{{year.group(0) if year else ''}}},\n"
                   f"  note = {{unverified; imported from DOCX reference [{n}]}}\n}}\n")
    return "\n".join(out)


def docx2tex(src: Path, out_dir: Path, title: Optional[str] = None) -> dict:
    src, out_dir = Path(src), Path(out_dir)
    doc = Document(str(src))
    sections_dir, fig_dir = out_dir / "sections", out_dir / "figures"
    sections_dir.mkdir(parents=True, exist_ok=True)
    cite_keys: Dict[int, str] = {}
    body: List[str] = []
    abstract: List[str] = []
    keywords = ""
    refs: List[Tuple[int, str]] = []
    doc_title = title or ""
    authors_raw: List[str] = []
    mode = "front"           # front -> body -> refs
    fig_counter = [0]
    tbl_counter = 0
    stats = {"paragraphs": 0, "headings": 0, "tables": 0, "figures": 0, "references": 0, "citations": 0}

    for kind, obj in iter_blocks(doc):
        if kind == "t":
            tbl_counter += 1
            stats["tables"] += 1
            body.append(table_tex(obj, tbl_counter, cite_keys))
            body.append("")
            continue
        p = obj
        text = p.text.strip()
        figs = extract_images(doc, p, fig_dir, fig_counter)
        if figs:
            stats["figures"] += len(figs)
            body += figs + [""]
        if not text:
            continue
        lvl = heading_level(p)
        upper = text.upper().rstrip(":—-")
        if mode == "front":
            if not doc_title and (lvl == 0 or (p.style is not None and p.style.name == "Title")):
                doc_title = esc(text)
                continue
            if not doc_title and len(authors_raw) == 0 and len(text) < 160 and lvl is None and not text.lower().startswith("abstract"):
                doc_title = esc(text)
                continue
            if upper.startswith("ABSTRACT"):
                abstract.append(esc(re.sub(r"^\s*Abstract\s*[—:\-]*\s*", "", text, flags=re.I)))
                continue
            if upper.startswith("INDEX TERMS") or upper.startswith("KEYWORDS") or upper.startswith("KATA KUNCI"):
                keywords = esc(re.sub(r"^\s*(Index Terms|Keywords|Kata Kunci)\s*[—:\-]*\s*", "", text, flags=re.I))
                continue
            if lvl is not None and lvl >= 1:
                mode = "body"
            elif abstract and not keywords and lvl is None and len(text) > 200:
                abstract.append(esc(text))
                continue
            else:
                authors_raw.append(text)
                continue
        if mode == "body":
            if upper in ("REFERENCES", "REFERENCE", "BIBLIOGRAPHY", "DAFTAR PUSTAKA") or (lvl and upper.startswith("REFERENCES")):
                mode = "refs"
                continue
            if lvl is not None and lvl >= 1:
                cmd = {1: "section", 2: "subsection", 3: "subsubsection"}[min(lvl, 3)]
                ht = esc(heading_text(p))
                label = re.sub(r"[^a-z0-9]+", "-", ht.lower()).strip("-")[:30]
                body += [f"\\{cmd}{{{ht}}}", f"\\label{{sec:{label}}}", ""]
                stats["headings"] += 1
                continue
            if "=" in text and len(text) < 120 and re.search(r"[=^_∑∫√±]", text) and len(text.split()) < 12:
                body += [f"\\todo{{equation: {esc(text)}}}", ""]
                continue
            stats["paragraphs"] += 1
            stats["citations"] += len(CITE_RE.findall(text))
            body += [para_tex(p, cite_keys), ""]
            continue
        if mode == "refs":
            m = REF_LINE_RE.match(text)
            if m:
                refs.append((int(m.group(1)), m.group(2).strip()))
            elif refs:
                n, prev = refs[-1]
                refs[-1] = (n, prev + " " + text)
            continue
    stats["references"] = len(refs)

    sec = []
    if abstract:
        sec += ["\\begin{abstract}", " ".join(abstract), "\\end{abstract}", ""]
    if keywords:
        sec += ["\\begin{IEEEkeywords}", keywords, "\\end{IEEEkeywords}", ""]
    sec += body
    (sections_dir / "body.tex").write_text("\n".join(sec).rstrip() + "\n", encoding="utf-8")

    authors_tex = "\\IEEEauthorblockN{\\todo{Author names}}\n\\IEEEauthorblockA{\\todo{Affiliation}}\n"
    if authors_raw:
        authors_tex = "% raw author lines from the DOCX:\n" + "".join(f"% {esc(a)}\n" for a in authors_raw) + authors_tex
    (out_dir / "main.tex").write_text(MAIN_TEMPLATE.format(src=src.name, title=doc_title or "\\todo{Title}",
                                                            authors=authors_tex), encoding="utf-8")
    cited = sorted(cite_keys)
    for n in cited:                                  # cited but not in the list -> still emit a key so LaTeX compiles
        if n not in {r[0] for r in refs}:
            refs.append((n, f"\\todo{{reference [{n}] missing from the DOCX reference list}}"))
    refs.sort()
    (out_dir / "references.bib").write_text(references_bib(refs, cite_keys), encoding="utf-8")
    seed = ["# Curate, then: paper-agent verify-refs --seed references_seed.yaml --bib references.bib --report references_report.md",
            "entries:"]
    for n, text in refs:
        year = re.search(r"\b(19|20)\d{2}\b", text)
        seed += [f"  - key: {cite_keys.get(n, f'ref{n}')}", "    type: misc",
                 f"    title: {_yaml_str(text[:200])}", "    authors: []",
                 f"    year: {year.group(0) if year else 'null'}", "    verify: auto",
                 f"    raw: {_yaml_str(text)}"]
    (out_dir / "references_seed.yaml").write_text("\n".join(seed) + "\n", encoding="utf-8")
    stats.update({"out_dir": str(out_dir), "title": doc_title, "author_lines": authors_raw})
    return stats


def _yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
